### ISSUE TITLE
missing brushes

### ISSUE THREAD

**Issue by Reaper10** [Deevad/deevad-krita-brushpresets#10]
i just updated to krita  4.0 on widows 10 desktop
Cervy line 
![capture](https://user-images.githubusercontent.com/8137561/38638464-f4842ccc-3d93-11e8-924a-11f7b7530708.PNG)

special dot and special fuzzy
![5](https://user-images.githubusercontent.com/8137561/38637294-5477926c-3d90-11e8-9277-b1371b04f6f9.png)

sketch speed point
![2](https://user-images.githubusercontent.com/8137561/38638029-88e1bb52-3d92-11e8-9517-be627bfd7a67.png)

quick circel 
![1](https://user-images.githubusercontent.com/8137561/38637737-a9438494-3d91-11e8-918e-f22ba430418d.png)

fuzzy texture 
![3](https://user-images.githubusercontent.com/8137561/38637700-8d03dfc2-3d91-11e8-918a-e44e5216fee5.png) 
i use these a lot could bring them back

**Comment by Deevad** [comment]
Hi, 
You can activate them by going to Manage Resources in the Settings ; and then activate the Krita_3_Default_Resources. 

The goal of Krita 4.x new brushes wasn't a simple upgrade of the brushes, but a rewrite.

**Comment by Deevad** [comment]
dialog screenshot : 

![2018-04-11_screenshot_212629](https://user-images.githubusercontent.com/4021867/38638627-30bd7190-3dcf-11e8-8043-48119ed87bf3.png)

**Comment by Reaper10** [comment]
thanks that helped 
i can't seem to find 
the dot spirl one
![38637294-5477926c-3d90-11e8-9277-b1371b04f6f9](https://user-images.githubusercontent.com/8137561/38645517-e895165e-3da9-11e8-96a7-73c9c9d62c6b.png)
this one

**Comment by Deevad** [comment]
Yes; the brush engine behind this brush preset was depreciated because too hard to maintain and too experimental.
