### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by razvanc-r** [Deevad/deevad-krita-brushpresets#4]
Hi and thanks for the great resource! :)

I'd like to add that it would probably be of great help to have proper tags on the brushes, so they're also very easily accessible from the favorites circle menu (something like the [modular brush set](https://vascobasque.com/modular-brushset/)). I'd do it myself but the tagging system is broken in krita v3 and I don't wan't to install v2.9 just to create the tags (cause it has a lot of dependencies as I'm not using kde)...

**Comment by Deevad** [comment]
Thank you for the feedback. 
At the moment, I propose in the bundle a single tag 'deevad' with 10 brush on it for the right-click pop-up palette. And Krita create a auto-tag for the whole bundle 'deevad-v8'. But it's defintely a good idea to add more tags.
What specific bug have you with tags? (bug report URL?).

**Comment by razvanc-r** [comment]
I didn't submit a bug report for the tags system cause I was asking about it in the IRC and the devs already know. I cannot assign brushes to tags or remove tags for that matter. I can only rename them and create new tags and that's pretty much it and it is kind of annoying cause I rely on the pop-up palette quite a bit :). But oh well, I really don't want to install krita 2.9 cause it has a lot of dependencies. I'll just wait for krita 3 to become stable and when the tag system will be fixed then I'll be able to modify as needed.

**Comment by Deevad** [comment]
>> I'll just wait for krita 3
Release is next week! :) I couldn't see the bug here ( tag system had bug fix last week) , I hope it will be fixed on your future install as well.

**Comment by razvanc-r** [comment]
I'm using the latest RC1 appimage but it still has this bug and I know boud and the guys know about the issues cause I've talked with them on the IRC, but yes, I hope it will be fixed in the stable release.

**Comment by razvanc-r** [comment]
Well they sure didn't fix the bugs in the v3 release :) oh well...

**Comment by Deevad** [comment]
I'm closing this issue as it's a todo for Krita-dev. Right now, tag system is too unstable to really play with. I keep all the brush with the tag 'deevad' only for quick way to isolate them. Thanks for the report again!
