### ISSUE TITLE
I can´t use the brush set - see no brushes

### ISSUE THREAD

**Issue by BogusCurry** [Deevad/deevad-krita-brushpresets#5]
Hello ;D At first thanks for the great set of brushes ;D
But I have a problem with the set, under Win7 64 bit and Linux Mint 64bit, krita 3.0. I can´t see the brushes set. I have activate the bundle under resources. I wonder, that no more ppl has this problem or I make wrong.

Edit: The set bundle folder was empty, I have move the file in this folder and so is the problem fixed ;D

Greetings

Bogus

**Comment by Deevad** [comment]
Hey,
Thanks for reporting the issue, and it's good to see you could solve the problem.
I'm closing this post, then. Enjoy painting/drawing ! :)
